# version: '3.8'

services:

  # nextjs:
  #   build:
  #     context: ./fullstack/next
  #   container_name: nextjs-app
  #   ports:
  #     - "3002:3000"
  #   volumes:
  #     - ./fullstack/next:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true # Necesario para live reload en Docker

  express:
    build:
      context: ./backend/express
    container_name: express-app
    ports:
      - "4000:4000"
    volumes:
      - ./backend/express:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Necesario para live reload en Docker

  # postgres:
  #   image: postgres:15
  #   container_name: postgres-db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: vitalnest
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin123
